# -*- coding: utf-8 -*-
"""task_tracker_cli.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NvAFP8bfHrmJd0bQxSQQvG8g0ZpkWdO7
"""

# task_tracker_cli.py

import csv
import os

FILENAME = "tasks.csv"

def add_task():
    file_exists = os.path.isfile(FILENAME)

    task_name = input("Enter task name: ")
    priority = input("Enter priority (High/Medium/Low): ")
    status = "Pending"

    with open(FILENAME, "a", newline="") as file:
        writer = csv.writer(file)
        if not file_exists:
            writer.writerow(["Task Name", "Priority", "Status"])
        writer.writerow([task_name, priority, status])

    print("Task added successfully!")

def view_tasks():
    if not os.path.exists(FILENAME):
        print("No tasks found.")
        return

    with open(FILENAME, "r") as file:
        reader = csv.reader(file)
        for row in reader:
            print(row)

def update_task():
    tasks = []
    with open(FILENAME, "r") as file:
        reader = csv.reader(file)
        header = next(reader)
        tasks = list(reader)

    for i, task in enumerate(tasks):
        print(i, task)

    index = int(input("Enter task index to update: "))
    new_status = input("Enter new status: ")

    tasks[index][2] = new_status

    with open(FILENAME, "w", newline="") as file:
        writer = csv.writer(file)
        writer.writerow(header)
        writer.writerows(tasks)

    print("Task updated!")

def menu():
    while True:
        print("\n1. Add Task")
        print("2. View Tasks")
        print("3. Update Task")
        print("4. Exit")

        choice = input("Choose option: ")

        if choice == "1":
            add_task()
        elif choice == "2":
            view_tasks()
        elif choice == "3":
            update_task()
        elif choice == "4":
            break
        else:
            print("Invalid choice")

menu()